### ISSUE TITLE
doc需要设置一下才能访问

### ISSUE THREAD

**Issue by YuzukiTsuru** [xboot/xfel#17]
具体是Settings -> Pages -> Source 选择 /docs

![QQ截图20211225174655](https://user-images.githubusercontent.com/12003087/147382425-40bb3783-5809-4c67-b1fe-1f6818b02e41.png)

**Comment by jianjunjiang** [comment]
已设置，可以访问docs目录了，但左侧边栏的favicon.ico没有能正确显示。
![2021-12-26 11-37-55屏幕截图](https://user-images.githubusercontent.com/89262/147398251-68b53cf8-f090-49b0-a593-c99abdd49fb9.png)

**Comment by YuzukiTsuru** [comment]
我检查一下

**Comment by YuzukiTsuru** [comment]
#18
