### ISSUE TITLE
错误：bulk send error

### ISSUE THREAD

**Issue by CornerOfSkyline** [xboot/xfel#24]
`xfel ddr ddr3`
`xfel ddr d1   - Initial ddr controller for D1`
`xfel ddr f133 - Initial ddr controller for F133`
`Failed to initial ddr controller`
`xfel write 0x40000000 zcore_d1.bin`
`usb bulk send error`

向D1-H上烧写时报“usb bulk send error”错误，重新编译xfel、重启电脑也都没有解决

**Comment by aozima** [comment]
这不是提示你命令中要指定芯片型号么

**Comment by CornerOfSkyline** [comment]
@aozima 看明白了，已搞定，谢谢
