### ISSUE TITLE
SPI nand write not enabling ECC.

### ISSUE THREAD

**Issue by deividAlfa** [xboot/xfel#28]
SPI chip is W25N01GV
Data is correctly read and written, but it seems the somehow the ECC (OOB area) is not being generated, breaking the filesystem.
I've played with the code, and ECC-E bit (Status-2 register) is actually enabled.
In the end I modified it further for my needings, disabling ECC and reading/writing raw 2112-byte pages.

**Comment by jianjunjiang** [comment]
yes， you are right， ECC is not support
