### ISSUE TITLE
连接d1-h开发板执行xfel ddr ddr3报错

### ISSUE THREAD

**Issue by TuringKi** [xboot/xfel#34]
平台：Mac OS X
版本：git clone 当前（2022-06-12）最新版
如题：
./xfel ddr ddr3
xfel ddr d1   - Initial ddr controller for D1
xfel ddr f133 - Initial ddr controller for F133
Failed to initial ddr controller

./xfel version执行结果：
./xfel version
AWUSBFEX ID=0x00185900(D1/F133) dflag=0x44 dlength=0x08 scratchpad=0x00045000

是我命令使用错误吗？

**Comment by jianjunjiang** [comment]
看提示，命令使用错误，准确命令：

```
xfel ddr d1 
```

**Comment by jianjunjiang** [comment]
问题关闭
