### ISSUE TITLE
xfel on XuanTie C906 RISC-V

### ISSUE THREAD

**Issue by BrunoSteven** [xboot/xfel#37]
用xfel时，将写入内存的文件读出后，发现和写入的有一定的区别，导致写入后的bin文件无法执行（不知道是不是我哪里做错了，麻烦看一下

![problem](https://user-images.githubusercontent.com/66072326/177346449-fd0ee4eb-67ac-406c-ac50-537abed32877.png)

**Comment by jianjunjiang** [comment]
你写到SRAM了吧，SRAM中有代码在运行的。
