### ISSUE TITLE
How to execute binaries?

### ISSUE THREAD

**Issue by juanschroeder** [xboot/xfel#38]
Hi guys,

Thanks for the work on this tool.
I am trying touse xfel for loading manually the binaries built for the D1 into RAM, building opensbi, u-boot, etc, manually. When I run:
`./xfel exec 0x40000000 BINARY`

I just don't see anything happen, nothing printed in the serial port and no response to xfel anymore. 
I've tried the full 'u-boot.toc1' full binary or loading and running openSBI, u-boot and u-boot DTB binaries directly and it's always the same result.
Can you tell me what I could be doing wrong?

Thanks

**Comment by jianjunjiang** [comment]
sudo xfel ddr d1;
sudo xfel write 0x40000000 xboot.bin; 
sudo xfel exec 0x40000000;
