### ISSUE TITLE
BROM firmware source code

### ISSUE THREAD

**Issue by guncha** [xboot/xfel#44]
Hello! I'm using MQ-Pro which uses the D1 chip and it works great with `xfel` so thank you for a great project! I'm wondering if source code for the firmware that `xfel` communicates with is available somewhere. I'd like to understand better how it works. Of course I can dump the assembly starting at 0x0, but it doesn't have any symbol information, and it looks like it's using undocumented memory regions such as `0x70005e0`. Thanks!

**Comment by jianjunjiang** [comment]
Not any brom source code, you can find some information in [linux-sunxi.org](http://linux-sunxi.org/)
