### ISSUE TITLE
下载特定文件出现usb bulk send error错误

### ISSUE THREAD

**Issue by wsr70** [xboot/xfel#46]
我用xfel烧写T113-S3的SPI NAND FLASH出现，只要烧写一个特定的dtb文件就会出现usb bulk send error，这个错误与烧写的地址无关，烧写其他文件都可以，只有烧写这特定文件才会出现，我换了两种开发板，现象是一至的。
这就是那个会导致错误的文件[board.dtb.gz](https://github.com/xboot/xfel/files/10556444/board.dtb.gz)

**Comment by jianjunjiang** [comment]
估计跟你烧写的位置有关，不要破坏SRAM中fel程序

**Comment by try-agaaain** [comment]
我遇到了同样的问题，SRAM中fel程序的地址范围是多少呀

**Comment by wsr70** [comment]
我下载的文件发生变化后，就没有再出现问题，我猜是下载的文件长度碰巧了是某个长度或下载的内容有某些特定内容造成的，与SRAM无关，毕竟下载时的命令是向FLASH中写入数据，你可以尝试改变文件的长度及内容，看看是否能解决。
