### ISSUE TITLE
Doesn't support A50

### ISSUE THREAD

**Issue by Fusseldieb** [xboot/xfel#49]
I'm trying to access an Allwinner A50 chip and get following message:
```
WARNING: Not yet support this device ID 0x00175500
ERROR: Can't found any FEL device
``` 

lsusb:
`Bus 001 Device 004: ID 1f3a:efe8 Allwinner Technology sunxi SoC OTG connector in FEL/flashing mode`

**Comment by jianjunjiang** [comment]
可以复制一份，增加对ID 0x00175500的支持

**Comment by jianjunjiang** [comment]
增加A50芯片ID识别支持
https://github.com/xboot/xfel/commit/8bcc3842ef90fb085a713048e7a078ec5552fc21
