### ISSUE TITLE
关于将 Makefile 编译方式升级到 CMake 方式的谈论

### ISSUE THREAD

**Issue by taotieren** [xboot/xfel#5]
- [ ] 处理跨平台编译的问题
    - [ ] Linux
    - [ ] Winodws
    - [ ] macOS
- [ ] 处理不同平台打包的问题
    - [ ] Linux
    - [ ] Winodws
    - [ ] macOS
- [ ] 处理 CI/CD 的问题
- [ ] 其他问题

**Comment by jianjunjiang** [comment]
简单的项目还是直接makefile吧，尽量避免引入太多复杂的组件。越简单越好！
