### ISSUE TITLE
spi at t113-s3/D1s

### ISSUE THREAD

**Issue by ua1arn** [xboot/xfel#51]
I propose two changes:
1) slow SPI speed (50 MHz too fast sometimes).
2) Add wait for clear start transfer bit before FIFO level check (required in user manual).
![image](https://user-images.githubusercontent.com/34999007/233030746-9914c942-92f2-4021-a221-0611ca922ef8.png)

**Comment by jianjunjiang** [comment]
50MHZ clock is no problem at all for spi nor flash

**Comment by jianjunjiang** [comment]
wait for clear start transfer bit before FIFO level check。

This is unnecessary, because there is waiting for the fifo to have enough remaining space, and then write to the fifo.

**Comment by ua1arn** [comment]
If transfer chunk size not equal to FIFO size, I got some problems if skipped transfer bit waiting.
