### ISSUE TITLE
usb bulk send error

### ISSUE THREAD

**Issue by try-agaaain** [xboot/xfel#56]
我写了一段hello world代码，通过xfel烧录到D1开发板上（LicheeRV Dock），我尝试烧录在0x40000000，虽然第一次能正常运行，但第二次执行时出现“usb bulk send error”。

我猜测是不是烧录的地址存在问题，于是修改程序将起始地址改为0x48000000，并在内存地址0x48000000处重新烧录，但也遇到了同样的问题：

![image](https://github.com/xboot/xfel/assets/52828870/782820a5-5225-4853-a872-761acad4b0ca)

为什么会出现这个问题呢？

**Comment by aozima** [comment]
⚠运行属于强跳，你的应用程序基本不再回来。
即使能回来，运行期间也没人维护USB状态，自然是断掉了。

✔重新上电进入FEL模式再重新加载就行了！

**Comment by try-agaaain** [comment]
好的，谢谢
