### ISSUE TITLE
xfel无法找到FEL设备

### ISSUE THREAD

**Issue by wangtao-creator** [xboot/xfel#8]
你好，大佬，我想咨询一个xfel在哪吒D1 C906上无法找到 FEL device的问题的问题。
我在虚拟机ubuntu14.04下按照xfel的步骤安装了xfel，之后按住开发板上的fel键再上电，使用xfel的时候出现这个错误：ERROR：Can’t found any FEL device。
我尝试过这些方法：1.在win10下使用windows版本的xfel，也是一样的报错。2.重新安装xfel。   3.重新安装串口驱动。
![image](https://user-images.githubusercontent.com/55620716/129727428-5d80c242-45bf-4072-bbef-5d6f2812017d.png)

**Comment by jianjunjiang** [comment]
windows下需要用zidag重新安装下驱动，不能使用全志官方的驱动，还有，需要确认你的D1处于FEL模式，可以在设备管理器里查看是否存在

**Comment by wangtao-creator** [comment]
谢谢大佬，我已经解决了。
