### ISSUE TITLE
请问怎样从spinand引导进入xboot

### ISSUE THREAD

**Issue by elliott10** [xboot/xfel#9]
请问怎样从spinand引导xboot呢？

**Comment by jianjunjiang** [comment]
这里有两个工作要做：

第一个是xboot要实现spi nand flash自拷贝，这个功能现在还没有实现，这个等我有了F133/D1s的板子后再开发了。
第二个就是烧写需要做些特殊处理，全志的brom引导spi nand flash时，每一个page不管page是2k还是4k的，都仅使用前面的1k（或者2k，这个需要去确认下），多余的空间必须空着，全志这样处理的目的是简化BROM的开发，以支持各种SPI nand flash 自举引导。具体spi nand 引导挖坑网有相关脚本，可以进行分析。

可以自行研究下，等我有板子了，再做进一步的开发。

**Comment by elliott10** [comment]
谢谢大佬的解答

**Comment by jianjunjiang** [comment]
全志RISC-V芯片F133/D1s SPI nand flash自举引导
https://zhuanlan.zhihu.com/p/443791648
